### ISSUE TITLE
[Question]RPCError

### ISSUE THREAD

**Issue by elchanly** [alfem/telegram-downloader-bot#25]
Hi! I'm getting this: Error: RPCError -503: Timedout (caused by GetFileRequest)
Not sure if this is a local problem caused by my connection or my server but it has been happening for a few days. Is there any way to further investigate ?

Thanks for your work on this marvelous bot

**Comment by alfem** [comment]
I am afraid the library _python-telegram-bot_ my script depends on has deeply changed. 
I'd had to rewrite the python script to make it compatible again.

I suggest to move to my other project, [Telegram-Download-Daemon](https://github.com/alfem/telegram-download-daemon). It uses a different approach (it uses the telegram user api instead of the bot api). It is more powerful and is better maintained.

**Comment by elchanly** [comment]
mmmm it seems im using that one. So sorry, but i wasnt aware there where 2 similar projects and just googled out your github and picked this. My docker compose uses that project you said. May I open issue there?

**Comment by alfem** [comment]
Yes, please.
